# Generated by Django 4.0.3 on 2022-03-12 16:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evening',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 12), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='nose',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='nose/Geruch (0-10)'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='taste/Geschmack (0-10)'),
        ),
    ]
