# Generated by Django 4.0.3 on 2022-03-12 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_evening_date_alter_tasting_nose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evening',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
