# Generated by Django 4.0.3 on 2022-03-13 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_evening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveningwhisky',
            name='order',
            field=models.IntegerField(null=True, verbose_name='order of the day'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='taste/Geschmack (0-10)'),
        ),
    ]
