# Generated by Django 4.0.3 on 2022-03-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_eveningwhisky_order_alter_tasting_taste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evening',
            options={'ordering': ['-date']},
        ),
    ]
