# Generated by Django 4.0.3 on 2022-03-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_evening_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eveningwhisky',
            options={'ordering': ['order'], 'verbose_name_plural': 'EveningWhiskies'},
        ),
    ]
