# Generated by Django 4.0.3 on 2022-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_eveningwhisky_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='taste/Geschmack (0-10)'),
        ),
    ]
