# Generated by Django 4.0.3 on 2022-03-14 09:10

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_tasting_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[catalog.models.validate_empty_or_0_10], verbose_name='taste/Geschmack (0-10)'),
        ),
    ]
