# Generated by Django 4.0.3 on 2022-03-20 10:02

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_tasting_color_tasting_smokiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='color',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[catalog.models.validate_empty_or_0_10], verbose_name='color/Farbe (0-10) like water=0, Cola=10'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='nose',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[catalog.models.validate_empty_or_0_10], verbose_name='nose/Geruch (0-10) best whisky ever=10'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='smokiness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[catalog.models.validate_empty_or_0_10], verbose_name='smokiness/Rauchigkeit (0-10) in the middle of the chimney=10'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[catalog.models.validate_empty_or_0_10], verbose_name='taste/Geschmack (0-10) best whisky ever=10'),
        ),
    ]
